# frozen_string_literal: true

FactoryBot.define do
  factory :github_repo do
    organization { 'vuejs' }
    project { 'vue' }
    category { :javascript_framework }
    data do
      {
        'id' => 11_730_342,
        'url' => 'https://api.github.com/repos/vuejs/vue',
        'fork' => false,
        'name' => 'vue',
        'size' => 31_720,
        'forks' => 32_599,
        'owner' => {
          'id' => 6_128_107,
          'url' => 'https://api.github.com/users/vuejs',
          'type' => 'Organization',
          'login' => 'vuejs',
          'node_id' => 'MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=',
          'html_url' => 'https://github.com/vuejs',
          'gists_url' => 'https://api.github.com/users/vuejs/gists{/gist_id}',
          'repos_url' => 'https://api.github.com/users/vuejs/repos',
          'avatar_url' => 'https://avatars.githubusercontent.com/u/6128107?v=4',
          'events_url' => 'https://api.github.com/users/vuejs/events{/privacy}',
          'site_admin' => false,
          'gravatar_id' => '',
          'starred_url' => 'https://api.github.com/users/vuejs/starred{/owner}{/repo}',
          'followers_url' => 'https://api.github.com/users/vuejs/followers',
          'following_url' => 'https://api.github.com/users/vuejs/following{/other_user}',
          'organizations_url' => 'https://api.github.com/users/vuejs/orgs',
          'subscriptions_url' => 'https://api.github.com/users/vuejs/subscriptions',
          'received_events_url' => 'https://api.github.com/users/vuejs/received_events'
        },
        'topics' => %w[framework frontend javascript vue],
        'git_url' => 'git://github.com/vuejs/vue.git',
        'license' => {
          'key' => 'mit',
          'url' => 'https://api.github.com/licenses/mit',
          'name' => 'MIT License',
          'node_id' => 'MDc6TGljZW5zZTEz',
          'spdx_id' => 'MIT'
        },
        'node_id' => 'MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==',
        'private' => false,
        'ssh_url' => 'git@github.com:vuejs/vue.git',
        'svn_url' => 'https://github.com/vuejs/vue',
        'archived' => false,
        'disabled' => false,
        'has_wiki' => true,
        'homepage' => 'http://vuejs.org',
        'html_url' => 'https://github.com/vuejs/vue',
        'keys_url' => 'https://api.github.com/repos/vuejs/vue/keys{/key_id}',
        'language' => 'TypeScript',
        'tags_url' => 'https://api.github.com/repos/vuejs/vue/tags',
        'watchers' => 198_450,
        'blobs_url' => 'https://api.github.com/repos/vuejs/vue/git/blobs{/sha}',
        'clone_url' => 'https://github.com/vuejs/vue.git',
        'forks_url' => 'https://api.github.com/repos/vuejs/vue/forks',
        'full_name' => 'vuejs/vue',
        'has_pages' => false,
        'hooks_url' => 'https://api.github.com/repos/vuejs/vue/hooks',
        'pulls_url' => 'https://api.github.com/repos/vuejs/vue/pulls{/number}',
        'pushed_at' => '2022-08-08T00:45:41Z',
        'teams_url' => 'https://api.github.com/repos/vuejs/vue/teams',
        'trees_url' => 'https://api.github.com/repos/vuejs/vue/git/trees{/sha}',
        'created_at' => '2013-07-29T03:24:51Z',
        'events_url' => 'https://api.github.com/repos/vuejs/vue/events',
        'has_issues' => true,
        'issues_url' => 'https://api.github.com/repos/vuejs/vue/issues{/number}',
        'labels_url' => 'https://api.github.com/repos/vuejs/vue/labels{/name}',
        'merges_url' => 'https://api.github.com/repos/vuejs/vue/merges',
        'mirror_url' => nil,
        'updated_at' => '2022-08-08T22:48:54Z',
        'visibility' => 'public',
        'archive_url' => 'https://api.github.com/repos/vuejs/vue/{archive_format}{/ref}',
        'commits_url' => 'https://api.github.com/repos/vuejs/vue/commits{/sha}',
        'compare_url' => 'https://api.github.com/repos/vuejs/vue/compare/{base}...{head}',
        'description' => 'a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
        'forks_count' => 32_599,
        'is_template' => false,
        'open_issues' => 577,
        'permissions' => { 'pull' => true, 'push' => false, 'admin' => false, 'triage' => false, 'maintain' => false },
        'branches_url' => 'https://api.github.com/repos/vuejs/vue/branches{/branch}',
        'comments_url' => 'https://api.github.com/repos/vuejs/vue/comments{/number}',
        'contents_url' => 'https://api.github.com/repos/vuejs/vue/contents/{+path}',
        'git_refs_url' => 'https://api.github.com/repos/vuejs/vue/git/refs{/sha}',
        'git_tags_url' => 'https://api.github.com/repos/vuejs/vue/git/tags{/sha}',
        'has_projects' => true,
        'organization' => {
          'id' => 6_128_107,
          'url' => 'https://api.github.com/users/vuejs',
          'type' => 'Organization',
          'login' => 'vuejs',
          'node_id' => 'MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=',
          'html_url' => 'https://github.com/vuejs',
          'gists_url' => 'https://api.github.com/users/vuejs/gists{/gist_id}',
          'repos_url' => 'https://api.github.com/users/vuejs/repos',
          'avatar_url' => 'https://avatars.githubusercontent.com/u/6128107?v=4',
          'events_url' => 'https://api.github.com/users/vuejs/events{/privacy}',
          'site_admin' => false,
          'gravatar_id' => '',
          'starred_url' => 'https://api.github.com/users/vuejs/starred{/owner}{/repo}',
          'followers_url' => 'https://api.github.com/users/vuejs/followers',
          'following_url' => 'https://api.github.com/users/vuejs/following{/other_user}',
          'organizations_url' => 'https://api.github.com/users/vuejs/orgs',
          'subscriptions_url' => 'https://api.github.com/users/vuejs/subscriptions',
          'received_events_url' => 'https://api.github.com/users/vuejs/received_events'
        },
        'releases_url' => 'https://api.github.com/repos/vuejs/vue/releases{/id}',
        'statuses_url' => 'https://api.github.com/repos/vuejs/vue/statuses/{sha}',
        'allow_forking' => true,
        'assignees_url' => 'https://api.github.com/repos/vuejs/vue/assignees{/user}',
        'downloads_url' => 'https://api.github.com/repos/vuejs/vue/downloads',
        'has_downloads' => true,
        'languages_url' => 'https://api.github.com/repos/vuejs/vue/languages',
        'network_count' => 32_599,
        'default_branch' => 'main',
        'milestones_url' => 'https://api.github.com/repos/vuejs/vue/milestones{/number}',
        'stargazers_url' => 'https://api.github.com/repos/vuejs/vue/stargazers',
        'watchers_count' => 198_450,
        'deployments_url' => 'https://api.github.com/repos/vuejs/vue/deployments',
        'git_commits_url' => 'https://api.github.com/repos/vuejs/vue/git/commits{/sha}',
        'subscribers_url' => 'https://api.github.com/repos/vuejs/vue/subscribers',
        'contributors_url' => 'https://api.github.com/repos/vuejs/vue/contributors',
        'issue_events_url' => 'https://api.github.com/repos/vuejs/vue/issues/events{/number}',
        'stargazers_count' => 198_450,
        'subscription_url' => 'https://api.github.com/repos/vuejs/vue/subscription',
        'temp_clone_token' => '',
        'collaborators_url' => 'https://api.github.com/repos/vuejs/vue/collaborators{/collaborator}',
        'issue_comment_url' => 'https://api.github.com/repos/vuejs/vue/issues/comments{/number}',
        'notifications_url' => 'https://api.github.com/repos/vuejs/vue/notifications{?since,all,participating}',
        'open_issues_count' => 577,
        'subscribers_count' => 6095,
        'web_commit_signoff_required' => false
      }
    end
  end

  trait :skip_validate do
    organization { 'non-existent-org' }
    to_create { |instance| instance.save(validate: false) }
  end
end
