version: "3"

services:
  postgres:
    image: "postgres:10-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: "redis:5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/project"
      - "/project/tmp" # don't mount tmp directory
    environment:
      - PGUSER=postgres
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  web:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    ports:
      - "3000:3000"
    volumes:
      - ".:/project"
    environment:
      - PGUSER=postgres
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  redis:
  postgres:
