development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - high
  - default
  - mailers
:scheduler:
  :schedule:
    update_github_repos:
      # Every night at midnight
      cron: "0 0 0 * * *"
      class: UpdateGithubReposJob
